export const ARWES_CORE_FRAME_CLASSNAME = 'arwes-frame';
export const ARWES_CORE_FRAME_LINE_CLASSNAME = `${ARWES_CORE_FRAME_CLASSNAME}__line`;
export const ARWES_CORE_FRAME_SHAPE_CLASSNAME = `${ARWES_CORE_FRAME_CLASSNAME}__shape`;
export const ARWES_CORE_FRAME_BG_CLASSNAME = `${ARWES_CORE_FRAME_CLASSNAME}__bg`;
export const ARWES_CORE_FRAME_BG_OPACITY = 0.2;
export const ARWES_CORE_FRAME_CONTENT_CLASSNAME = `${ARWES_CORE_FRAME_CLASSNAME}__content`;
