/* eslint-disable */

export default [
  { name: 'sounds/SoundsProvider', component: require('../packages/sounds/src/SoundsProvider/sandbox.js').default },
  { name: 'arwes/ThemeProvider', component: require('../packages/arwes/src/ThemeProvider/sandbox.js').default },
  { name: 'arwes/Arwes', component: require('../packages/arwes/src/Arwes/sandbox.js').default },
  { name: 'arwes/Words', component: require('../packages/arwes/src/Words/sandbox.js').default },
  { name: 'arwes/Heading', component: require('../packages/arwes/src/Heading/sandbox.js').default },
  { name: 'arwes/Paragraph', component: require('../packages/arwes/src/Paragraph/sandbox.js').default },
  { name: 'arwes/Link', component: require('../packages/arwes/src/Link/sandbox.js').default },
  { name: 'arwes/Blockquote', component: require('../packages/arwes/src/Blockquote/sandbox.js').default },
  { name: 'arwes/List', component: require('../packages/arwes/src/List/sandbox.js').default },
  { name: 'arwes/Content', component: require('../packages/arwes/src/Content/sandbox.js').default },
  { name: 'arwes/Frame', component: require('../packages/arwes/src/Frame/sandbox.js').default },
  { name: 'arwes/Button', component: require('../packages/arwes/src/Button/sandbox.js').default },
  { name: 'arwes/Line', component: require('../packages/arwes/src/Line/sandbox.js').default },
  { name: 'arwes/Loading', component: require('../packages/arwes/src/Loading/sandbox.js').default },
  { name: 'arwes/Image', component: require('../packages/arwes/src/Image/sandbox.js').default },
  { name: 'arwes/Code', component: require('../packages/arwes/src/Code/sandbox.js').default },
  { name: 'arwes/Table', component: require('../packages/arwes/src/Table/sandbox.js').default },
  { name: 'arwes/Project', component: require('../packages/arwes/src/Project/sandbox.js').default },
  { name: 'arwes/Header', component: require('../packages/arwes/src/Header/sandbox.js').default },
  { name: 'arwes/Footer', component: require('../packages/arwes/src/Footer/sandbox.js').default },
  { name: 'arwes/Grid', component: require('../packages/arwes/src/Grid/sandbox.js').default },
  { name: 'arwes/Animation', component: require('../packages/arwes/src/Animation/sandbox.js').default },
  { name: 'arwes/Appear', component: require('../packages/arwes/src/Appear/sandbox.js').default },
  { name: 'arwes/Highlight', component: require('../packages/arwes/src/Highlight/sandbox.js').default },
  { name: 'arwes/Puffs', component: require('../packages/arwes/src/Puffs/sandbox.js').default },
  { name: 'arwes/Logo', component: require('../packages/arwes/src/Logo/sandbox.js').default }
];
